import Article from '../../components/article/Article';
import TextBlock from '../../components/article/TextBlock';
import TitleBlock from '../../components/article/TitleBlock';

const PaperPython = () => {
  return (
    <Article>
      <TitleBlock title="Paper Python" />
      <TextBlock text="I first picked up coding after deciding I didn't want to be an artist. I had left uni and didn't have any idea what I wanted to do with my life. Since what I had been doing wasn't working, I tried a bunch of new things. I got into kayaking and got a teaching certificate for that, I learned to bake, and I started coding. In a strange way, it was everything I loved about art - being able to construct programs from lines of code was pure creation, like watching fractal snowflakes emerge from nothing. I played around with it for a while before deciding that this was something I wanted to do every day professionally." sectionTitle="Fractal Snowflakes" />
      <TextBlock text="I was fascinated by AI, so I decided I would study it at university - my second attempt at a degree. Of course, it wasn't quite so easy. I needed better grades to qualify for the course, so I enrolled in a program at my local college to redo my A-Levels. It took a year, and I passed with high marks. I applied to several universities and settled on Heriot-Watt in Edinburgh, partly for its reputation but also because I had always loved the city. It had taken a lot of effort, and I was very excited to start. I wanted to learn from the best, learn how to make exciting programs and understand the deep math that made AI work. I thought that this would be how I would become a great programmer." sectionTitle="" />
      <TextBlock text="It didn't quite turn out that way. I very quickly found out that uni wasn't about learning - it was about getting a grade. Creativity and effort weren't rewarded if they didn't check all the boxes for a project. Lectures were just reading chapters from a book. Homework seemed disconnected from the reality of coding that I had seen when I was teaching myself." sectionTitle="The Disconnect" />
      <TextBlock text="That's not to say I didn't enjoy uni. I learned almost nothing and ended up being a tutor for most of my classmates on what I thought was very basic material, but I got to experience living alone, making friends outside of my hometown, joining clubs and exploring the city. I explored castles and parks, went to parties, even fell in with a group of fire spinners when I stumbled on them during a midnight walk. But I went to uni to learn and to build a career, and I didn't feel like that was happening." sectionTitle="" />
      <TextBlock text="I tried to make it work at first. I remember the first project we had. We were using Blocky, a graphical way of building code out of blocks. I was already fluent in Java, but a lot of people had come with no background in coding at all, so Blocky was their way of bringing everyone up to the same level. It was slow for me, but I decided it didn't matter what you were coding with - you could still make something extraordinary if you were creative and smart." sectionTitle="Brick Breaker" />
      <TextBlock text="The assignment was to make a simple game. Most people went for something like Pong or image puzzle sliders. I decided to make Brick Breaker from scratch. I wanted to make it a personal challenge, making something amazing within the limits of Blocky. I created my own pixel art, decided on a color scheme. I spent hours forcing the Blocky blocks into complex objects and game loops. The hardest bit was the processing constraints - Blocky was nowhere near as efficient as a real programming language and it was easy to make the game lag. It took me a week, but it ran perfectly. It was elegant, clever, beautiful. The blocks had sparkle animations and sound effects when they were hit." sectionTitle="" />
      <TextBlock text="I was really proud of myself. Here was a class that was way below my level, but I had turned it into an opportunity to learn and be creative and excited. I very nearly failed. The teachers didn't care about my clever solutions or the optimizations of Blocky. They didn't want to play the game. All that mattered was that I was supposed to have been using as many of the components as possible - like checkboxes and inputs - and instead I had used only a few to make my complex game. I was devastated." sectionTitle="" />
      <TextBlock text="It reached a crisis point when we started doing exams. There was an exam on Python. I was confident about it - I knew Python, I was happy writing code in it, and I'd been building multiple programs in my own time. I thought it would be an easy A. But we were brought into the gym to sit on little wooden desks. Phones were removed, internet access and reference books were forbidden, and instead of computers we were given exam sheets. One of the questions was to write out functional code." sectionTitle="The Absurdity" />
      <TextBlock text="I couldn't believe it. It was such an utter divorce from reality. You don't write code on paper with no references - it makes no sense. Even now I forget how to write a for loop in a particular language because it doesn't matter. That's what Google and books and IDEs are for. The real knowledge in programming is being able to think in systems and the abstract, being able to hold an entire program in your head and understand it. I realized that if this was the kind of exam they were giving computer science students, then the degree had no value at all. I didn't want to be someone who left after four years with an impressive piece of paper and no idea what I was actually doing. I wanted to be learning and improving." sectionTitle="" />
      <TextBlock text="I went home and started researching jobs, pretending that I was actually applying for them. I wanted a career, and instead of assuming a degree was part of that, I decided to see what was actually required. A degree wasn't needed. Oh, lots of employers would have liked one, but what actually mattered was a portfolio - something to demonstrate that you had the practical skills to do the job. I realized that employers saw things the same way I did. They didn't want people with a piece of paper and no idea how to code. They wanted people who knew what they were doing, people who were self-directed enough to make their own projects." sectionTitle="Portfolios Over Paper" />
      <TextBlock text="I'd like to say quitting the course was a hard decision for me, but it wasn't. I knew staying was the wrong path, and I knew it wasn't aligning with my values. It hurt - it meant I had to go back to my parents and what felt like square one, and it meant leaving my friends and the home I was beginning to make in Edinburgh. But I knew that if I wanted to be a real programmer, then it was what I had to do." sectionTitle="Leaving Edinburgh" />
    </Article>
  );
};

export default PaperPython;

